<?php

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            [
                'name' => 'Oat Barister',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 1,
                'category_id' => 7,
                'image_link1' => "images/product/oat-barister.jpg",
                'image_link2'=> "images/product/oat-barister.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
        
            [
                'name' => 'Stephens Cocoa',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 7,
                'promotion' => 0,
                'image_link1' => "images/product/stephens-cocoa.jpg",
                'image_link2'=> "images/product/stephens-cocoa.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'B&G CUVEE',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 6,
                'image_link1' => "images/product/Drink.jpg",
                'image_link2'=> "images/product/Drink.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Andre Rose',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 6,
                'image_link1' => "images/product/Drink.jpg",
                'image_link2'=> "images/product/Drink.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Brown Bag',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 1,
                'category_id' => 2,
                'image_link1' => "images/product/product-02.jpg",
                'image_link2'=> "images/product/product-02-02.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Blue Long Sleeve',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 1,
                'image_link1' => "images/product/product-05.jpg",
                'image_link2'=> "images/product/product-05.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Blue Denim Shoe',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 3,
                'image_link1' => "images/product/product-45.jpg",
                'image_link2'=> "images/product/product-45-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'White Skin belt',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 4,
                'promotion' => 0,
                'image_link1' => "images/product/product-23.jpg",
                'image_link2'=> "images/product/product-23.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Female Sneaker',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 3,
                'image_link1' => "images/product/product-21.jpg",
                'image_link2'=> "images/product/product-21.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
           
            [
                'name' => 'Flared Shirt',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 1,
                'promotion' => 0,
                'image_link1' => "images/product/product-32-01.jpg",
                'image_link2'=> "images/product/product-32-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Glasses',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 4,
                'image_link1' => "images/product/product-24.jpg",
                'image_link2'=> "images/product/product-24.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'White Polo',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 1,
                'image_link1' => "images/product/product-31.jpg",
                'image_link2'=> "images/product/product-31.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            
            //    here...................

            [
                'name' => 'Juice Extractor',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 9,
                'image_link1' => "images/product/juice-extractor.jpg",
                'image_link2'=> "images/product/juice-extractor.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Skipping Rope',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 8,
                'image_link1' => "images/product/skipping-rope.jpg",
                'image_link2'=> "images/product/skipping-rope.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
        
            [
                'name' => 'Buzz Light Year',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/buzz-light-year.jpg",
                'image_link2'=> "images/product/buzz-light-year.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Puzzle',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/puzzle-toy.jpg",
                'image_link2'=> "images/product/puzzle-toy.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Lego Set',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/lego-set.jpg",
                'image_link2'=> "images/product/lego-set.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Johnnie Walker',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 7,
                'image_link1' => "images/product/johnnie-walker.jpg",
                'image_link2'=> "images/product/johnnie-walker.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Head Phone',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 4,
                'image_link1' => "images/product/headphone-01.jpg",
                'image_link2'=> "images/product/headphone-02.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'IPhone 11',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 11,
                'image_link1' => "images/product/iphone-11-01.jpg",
                'image_link2'=> "images/product/iphone-11-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'IPhone Airpods',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 11,
                'image_link1' => "images/product/iphone-11-airpods.jpg",
                'image_link2'=> "images/product/iphone-11-airpods.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Samsung S9',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 10,
                'image_link1' => "images/product/samsung-s9-01.jpg",
                'image_link2'=> "images/product/samsung-s9-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Samsung Charger',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 10,
                'image_link1' => "images/product/samsung-charger.jpg",
                'image_link2'=> "images/product/samsung-charger.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Tecno Pouvoir 3 Pro',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 12,
                'image_link1' => "images/product/TECNO-Pouvoir.jpg",
                'image_link2'=> "images/product/TECNO-Pouvoir.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Dumb Bell',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 8,
                'promotion' => 0,
                'image_link1' => "images/product/dumb-bells.jpg",
                'image_link2'=> "images/product/dumb-bells.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],  

            [
                'name' => 'Oat Barister',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 1,
                'category_id' => 7,
                'image_link1' => "images/product/oat-barister.jpg",
                'image_link2'=> "images/product/oat-barister.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
        
            [
                'name' => 'Stephens Cocoa',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 7,
                'promotion' => 0,
                'image_link1' => "images/product/stephens-cocoa.jpg",
                'image_link2'=> "images/product/stephens-cocoa.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'B&G CUVEE',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 6,
                'image_link1' => "images/product/Drink.jpg",
                'image_link2'=> "images/product/Drink.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Andre Rose',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 6,
                'image_link1' => "images/product/Drink.jpg",
                'image_link2'=> "images/product/Drink.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Brown Bag',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 1,
                'category_id' => 2,
                'image_link1' => "images/product/product-02.jpg",
                'image_link2'=> "images/product/product-02-02.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Blue Long Sleeve',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 1,
                'image_link1' => "images/product/product-05.jpg",
                'image_link2'=> "images/product/product-05.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Blue Denim Shoe',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 3,
                'image_link1' => "images/product/product-45.jpg",
                'image_link2'=> "images/product/product-45-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'White Skin belt',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 4,
                'promotion' => 0,
                'image_link1' => "images/product/product-23.jpg",
                'image_link2'=> "images/product/product-23.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Female Sneaker',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 3,
                'image_link1' => "images/product/product-21.jpg",
                'image_link2'=> "images/product/product-21.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
           
            [
                'name' => 'Flared Shirt',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 1,
                'promotion' => 0,
                'image_link1' => "images/product/product-32-01.jpg",
                'image_link2'=> "images/product/product-32-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Glasses',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 4,
                'image_link1' => "images/product/product-24.jpg",
                'image_link2'=> "images/product/product-24.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'White Polo',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 1,
                'image_link1' => "images/product/product-31.jpg",
                'image_link2'=> "images/product/product-31.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            
            //    here...................

            [
                'name' => 'Juice Extractor',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 9,
                'image_link1' => "images/product/juice-extractor.jpg",
                'image_link2'=> "images/product/juice-extractor.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Skipping Rope',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 8,
                'image_link1' => "images/product/skipping-rope.jpg",
                'image_link2'=> "images/product/skipping-rope.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
        
            [
                'name' => 'Buzz Light Year',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/buzz-light-year.jpg",
                'image_link2'=> "images/product/buzz-light-year.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Puzzle',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/puzzle-toy.jpg",
                'image_link2'=> "images/product/puzzle-toy.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Lego Set',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/lego-set.jpg",
                'image_link2'=> "images/product/lego-set.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Johnnie Walker',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 7,
                'image_link1' => "images/product/johnnie-walker.jpg",
                'image_link2'=> "images/product/johnnie-walker.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Head Phone',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 4,
                'image_link1' => "images/product/headphone-01.jpg",
                'image_link2'=> "images/product/headphone-02.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'IPhone 11',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 11,
                'image_link1' => "images/product/iphone-11-01.jpg",
                'image_link2'=> "images/product/iphone-11-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'IPhone Airpods',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 11,
                'image_link1' => "images/product/iphone-11-airpods.jpg",
                'image_link2'=> "images/product/iphone-11-airpods.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Samsung S9',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 10,
                'image_link1' => "images/product/samsung-s9-01.jpg",
                'image_link2'=> "images/product/samsung-s9-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Samsung Charger',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 10,
                'image_link1' => "images/product/samsung-charger.jpg",
                'image_link2'=> "images/product/samsung-charger.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Tecno Pouvoir 3 Pro',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 12,
                'image_link1' => "images/product/TECNO-Pouvoir.jpg",
                'image_link2'=> "images/product/TECNO-Pouvoir.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Dumb Bell',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 8,
                'promotion' => 0,
                'image_link1' => "images/product/dumb-bells.jpg",
                'image_link2'=> "images/product/dumb-bells.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],  

            [
                'name' => 'Juice Extractor',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 9,
                'image_link1' => "images/product/juice-extractor.jpg",
                'image_link2'=> "images/product/juice-extractor.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Skipping Rope',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 8,
                'image_link1' => "images/product/skipping-rope.jpg",
                'image_link2'=> "images/product/skipping-rope.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
        
            [
                'name' => 'Buzz Light Year',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/buzz-light-year.jpg",
                'image_link2'=> "images/product/buzz-light-year.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Puzzle',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/puzzle-toy.jpg",
                'image_link2'=> "images/product/puzzle-toy.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Lego Set',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/lego-set.jpg",
                'image_link2'=> "images/product/lego-set.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Johnnie Walker',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 7,
                'image_link1' => "images/product/johnnie-walker.jpg",
                'image_link2'=> "images/product/johnnie-walker.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Head Phone',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 4,
                'image_link1' => "images/product/headphone-01.jpg",
                'image_link2'=> "images/product/headphone-02.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'IPhone 11',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 11,
                'image_link1' => "images/product/iphone-11-01.jpg",
                'image_link2'=> "images/product/iphone-11-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'IPhone Airpods',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 11,
                'image_link1' => "images/product/iphone-11-airpods.jpg",
                'image_link2'=> "images/product/iphone-11-airpods.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Samsung S9',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 10,
                'image_link1' => "images/product/samsung-s9-01.jpg",
                'image_link2'=> "images/product/samsung-s9-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Samsung Charger',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 10,
                'image_link1' => "images/product/samsung-charger.jpg",
                'image_link2'=> "images/product/samsung-charger.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Tecno Pouvoir 3 Pro',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 12,
                'image_link1' => "images/product/TECNO-Pouvoir.jpg",
                'image_link2'=> "images/product/TECNO-Pouvoir.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Dumb Bell',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 8,
                'promotion' => 0,
                'image_link1' => "images/product/dumb-bells.jpg",
                'image_link2'=> "images/product/dumb-bells.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],  

            [
                'name' => 'Oat Barister',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 1,
                'category_id' => 7,
                'image_link1' => "images/product/oat-barister.jpg",
                'image_link2'=> "images/product/oat-barister.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
        
            [
                'name' => 'Stephens Cocoa',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 7,
                'promotion' => 0,
                'image_link1' => "images/product/stephens-cocoa.jpg",
                'image_link2'=> "images/product/stephens-cocoa.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'B&G CUVEE',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 6,
                'image_link1' => "images/product/Drink.jpg",
                'image_link2'=> "images/product/Drink.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Andre Rose',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 6,
                'image_link1' => "images/product/Drink.jpg",
                'image_link2'=> "images/product/Drink.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Brown Bag',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 1,
                'category_id' => 2,
                'image_link1' => "images/product/product-02.jpg",
                'image_link2'=> "images/product/product-02-02.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Blue Long Sleeve',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 1,
                'image_link1' => "images/product/product-05.jpg",
                'image_link2'=> "images/product/product-05.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Blue Denim Shoe',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 3,
                'image_link1' => "images/product/product-45.jpg",
                'image_link2'=> "images/product/product-45-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'White Skin belt',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 4,
                'promotion' => 0,
                'image_link1' => "images/product/product-23.jpg",
                'image_link2'=> "images/product/product-23.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Female Sneaker',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 3,
                'image_link1' => "images/product/product-21.jpg",
                'image_link2'=> "images/product/product-21.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
           
            [
                'name' => 'Flared Shirt',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 1,
                'promotion' => 0,
                'image_link1' => "images/product/product-32-01.jpg",
                'image_link2'=> "images/product/product-32-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Glasses',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 4,
                'image_link1' => "images/product/product-24.jpg",
                'image_link2'=> "images/product/product-24.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'White Polo',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 1,
                'image_link1' => "images/product/product-31.jpg",
                'image_link2'=> "images/product/product-31.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            
            //    here...................

            [
                'name' => 'Juice Extractor',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 9,
                'image_link1' => "images/product/juice-extractor.jpg",
                'image_link2'=> "images/product/juice-extractor.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Skipping Rope',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 8,
                'image_link1' => "images/product/skipping-rope.jpg",
                'image_link2'=> "images/product/skipping-rope.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
        
            [
                'name' => 'Buzz Light Year',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/buzz-light-year.jpg",
                'image_link2'=> "images/product/buzz-light-year.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Puzzle',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/puzzle-toy.jpg",
                'image_link2'=> "images/product/puzzle-toy.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Lego Set',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 5,
                'image_link1' => "images/product/lego-set.jpg",
                'image_link2'=> "images/product/lego-set.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Johnnie Walker',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 7,
                'image_link1' => "images/product/johnnie-walker.jpg",
                'image_link2'=> "images/product/johnnie-walker.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Head Phone',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 4,
                'image_link1' => "images/product/headphone-01.jpg",
                'image_link2'=> "images/product/headphone-02.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'IPhone 11',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 11,
                'image_link1' => "images/product/iphone-11-01.jpg",
                'image_link2'=> "images/product/iphone-11-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'IPhone Airpods',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 11,
                'image_link1' => "images/product/iphone-11-airpods.jpg",
                'image_link2'=> "images/product/iphone-11-airpods.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Samsung S9',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 10,
                'image_link1' => "images/product/samsung-s9-01.jpg",
                'image_link2'=> "images/product/samsung-s9-01.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Samsung Charger',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 10,
                'image_link1' => "images/product/samsung-charger.jpg",
                'image_link2'=> "images/product/samsung-charger.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],

            [
                'name' => 'Tecno Pouvoir 3 Pro',
                'description'=> 'Some random description for the product Some random description for the product  Some random description for the product  ',
                'promotion' => 0,
                'category_id' => 12,
                'image_link1' => "images/product/TECNO-Pouvoir.jpg",
                'image_link2'=> "images/product/TECNO-Pouvoir.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],
            [
                'name' => 'Dumb Bell',
                'description'=> 'Some random description for the product ome random description for the product ome random description for the product ome random description for the product ome random description for the product',
                'promotion' => 0,
                'category_id' => 8,
                'promotion' => 0,
                'image_link1' => "images/product/dumb-bells.jpg",
                'image_link2'=> "images/product/dumb-bells.jpg",
                'image_link3'=> "",
                'inventory_qty' => 100,
            ],  
        ];
        foreach($products as $product) {
            DB::table('products')->insert($product);
        }
    }
}
